export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';


export const INIT_STOCKS_START = 'INIT_STOCKS_START';
export const INIT_STOCKS_SUCCESS = 'INIT_STOCKS_SUCCESS';
export const INIT_STOCKS_ERROR = 'INIT_STOCKS_ERROR';


export const ADD_STOCK_START = 'ADD_STOCK_START';
export const ADD_STOCK_SUCCESS = 'ADD_STOCK_SUCCESS';
export const ADD_STOCK_ERROR = 'ADD_STOCK_ERROR';


export const DELETE_STOCK_START = 'DELETE_STOCK_START';
export const DELETE_STOCK_SUCCESS = 'DELETE_STOCK_SUCCESS';
export const DELETE_STOCK_ERROR = 'DELETE_STOCK_ERROR';


export const DISPATCH_STOCK_START = 'DISPATCH_STOCK_START';
export const DISPATCH_STOCK_SUCCESS = 'DISPATCH_STOCK_SUCCESS';
export const DISPATCH_STOCK_ERROR = 'DISPATCH_STOCK_ERROR';


export const ADD_DRIVER_START = 'ADD_DRIVER_START';
export const ADD_DRIVER_SUCCESS = 'ADD_DRIVER_SUCCESS';
export const ADD_DRIVER_ERROR = 'ADD_DRIVER_ERROR';